/*
 * generated by Xtext 2.14.0
 */
package info.scce.cinco.product.aiProject.gratext.ide;


/**
 * Use this class to register ide components.
 */
public class AIProjectGratextIdeModule extends AbstractAIProjectGratextIdeModule {
}
