/*
 * generated by Xtext 2.14.0
 */
package info.scce.cinco.product.aiProject.gratext.parser.antlr;

import com.google.inject.Inject;
import info.scce.cinco.product.aiProject.gratext.parser.antlr.internal.InternalAIProjectGratextParser;
import info.scce.cinco.product.aiProject.gratext.services.AIProjectGratextGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class AIProjectGratextParser extends AbstractAntlrParser {

	@Inject
	private AIProjectGratextGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE__WS", "RULE__ML_COMMENT", "RULE__SL_COMMENT");
	}
	

	@Override
	protected InternalAIProjectGratextParser createParser(XtextTokenStream stream) {
		return new InternalAIProjectGratextParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "AIProject";
	}

	public AIProjectGratextGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AIProjectGratextGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
