/*
 * generated by Xtext 2.14.0
 */
package info.scce.cinco.product.aiProject.gratext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAIProjectGratextScopeProvider extends DelegatingScopeProvider {
}
