/*
 * generated by Xtext 2.14.0
 */
package info.scce.cinco.product.aiProject.gratext.ui;

import com.google.inject.Injector;
import info.scce.cinco.product.aiProject.gratext.ui.internal.GratextActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AIProjectGratextExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(GratextActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		GratextActivator activator = GratextActivator.getInstance();
		return activator != null ? activator.getInjector(GratextActivator.INFO_SCCE_CINCO_PRODUCT_AIPROJECT_GRATEXT_AIPROJECTGRATEXT) : null;
	}

}
