/*
 * generated by Xtext 2.14.0
 */
package info.scce.cinco.product.aiProject.gratext.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
public class AIProjectGratextOutlineTreeProvider extends DefaultOutlineTreeProvider {

}
