/*
 * generated by Xtext 2.14.0
 */
package info.scce.cinco.product.aiProject.gratext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class AIProjectGratextUiModule extends AbstractAIProjectGratextUiModule {

	public AIProjectGratextUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
